In [2]:
import pandas as pd

In [3]:
k_s = pd.read_csv(r'/content/Kolkata_Sales.xls')

In [4]:
k_s

,TransactionID,CustomerID,OrderDate,Area,Product,Category,Qty,UnitPrice,PaymentMode
0,TXN0001,CUST041,2025-05-06,Gariahat,Kurti,Clothing,NaN,600.0,NaN
1,TXN0002,CUST058,2025-02-17,Dum Dum,Kurti,Clothing,1.0,150.0,Cash
2,TXN0003,CUST013,2025-01-04,New Market,Rosogolla Tin,Food,2.0,600.0,Cash
3,TXN0004,CUST014,2025-02-19,Park Street,Tea Packet,Grocery,1.0,1200.0,UPI
4,TXN0005,CUST047,2025-10-10,Park Street,Punjabi,Clothing,2.0,250.0,Card
...,...,...,...,...,...,...,...,...,...
253,TXN0162,CUST053,2025-01-28,Behala,Punjabi,Clothing,1.0,1200.0,UPI
254,TXN0092,CUST006,2025-11-28,Park Street,Fish (Rui),Food,2.0,250.0,Cash
255,TXN0225,CUST031,2025-08-01,Ballygunge,Sweets Box,Food,NaN,800.0,Cash
256,TXN0059,CUST002,2025-04-04,Dum Dum,Kurti,Clothing,1.0,NaN,UPI
257,TXN0235,CUST049,2025-11-11,gariahat,Kurti,Clothing,5.0,1200.0,Cash

In [5]:
k_s.isna()

,TransactionID,CustomerID,OrderDate,Area,Product,Category,Qty,UnitPrice,PaymentMode
0,False,False,False,False,False,False,True,False,True
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
253,False,False,False,False,False,False,False,False,False
254,False,False,False,False,False,False,False,False,False
255,False,False,False,False,False,False,True,False,False
256,False,False,False,False,False,False,False,True,False
257,False,False,False,False,False,False,False,False,False

In [6]:
k_s.dropna()

,TransactionID,CustomerID,OrderDate,Area,Product,Category,Qty,UnitPrice,PaymentMode
1,TXN0002,CUST058,2025-02-17,Dum Dum,Kurti,Clothing,1.0,150.0,Cash
2,TXN0003,CUST013,2025-01-04,New Market,Rosogolla Tin,Food,2.0,600.0,Cash
3,TXN0004,CUST014,2025-02-19,Park Street,Tea Packet,Grocery,1.0,1200.0,UPI
4,TXN0005,CUST047,2025-10-10,Park Street,Punjabi,Clothing,2.0,250.0,Card
5,TXN0006,CUST037,2025-05-29,Park Street,Fish (Rui),Food,1.0,450.0,UPI
...,...,...,...,...,...,...,...,...,...
251,TXN0250,CUST004,2025-01-04,Park Street,Saree,Clothing,5.0,150.0,UPI
252,TXN0231,CUST003,2025-11-25,Dum Dum,Jute Bag,Accessories,1.0,300.0,UPI
253,TXN0162,CUST053,2025-01-28,Behala,Punjabi,Clothing,1.0,1200.0,UPI
254,TXN0092,CUST006,2025-11-28,Park Street,Fish (Rui),Food,2.0,250.0,Cash
257,TXN0235,CUST049,2025-11-11,gariahat,Kurti,Clothing,5.0,1200.0,Cash

In [7]:
k_s.to_csv('Kolkata_sales.csv', index=False)

In [8]:
Kc = pd.read_csv('/content/kolkata_customers.csv')

In [9]:
Kc.head()

  CustomerID        CustomerName     HomeArea    JoinDate Membership
0    CUST001  Debashish Karmakar   New Market  2024-06-01    regular
1    CUST002       Riya Karmakar   Ballygunge  2024-11-06    regular
2    CUST003      Suroj Karmakar      Dum Dum  2023-01-13       Gold
3    CUST004  Rajarshi Mukherjee       Howrah  2023-01-18        NaN
4    CUST005         Poulomi Das  Park Street  2023-04-09        NaN

In [10]:
Kc['Membership'] = Kc['Membership'].replace('regular', 'Ragular')

In [11]:
display(Kc.head())

  CustomerID        CustomerName     HomeArea    JoinDate Membership
0    CUST001  Debashish Karmakar   New Market  2024-06-01    Ragular
1    CUST002       Riya Karmakar   Ballygunge  2024-11-06    Ragular
2    CUST003      Suroj Karmakar      Dum Dum  2023-01-13       Gold
3    CUST004  Rajarshi Mukherjee       Howrah  2023-01-18        NaN
4    CUST005         Poulomi Das  Park Street  2023-04-09        NaN

In [12]:
Kc.dropna()

   CustomerID         CustomerName     HomeArea    JoinDate Membership
0     CUST001   Debashish Karmakar   New Market  2024-06-01    Ragular
1     CUST002        Riya Karmakar   Ballygunge  2024-11-06    Ragular
2     CUST003       Suroj Karmakar      Dum Dum  2023-01-13       Gold
6     CUST007    Tanmoy Chatterjee       Howrah  2025-03-25    Ragular
8     CUST009       Sneha Banerjee       Howrah  2024-12-01       Gold
9     CUST010         Ananya Ghosh      Dum Dum  2024-01-24    Ragular
10    CUST011          Nandini Sen     Gariahat  2024-10-14       Gold
11    CUST012        Moumita Ghosh   Ballygunge  2025-05-15    Ragular
12    CUST013          Souvik Bose  Park Street  2024-06-24       Gold
13    CUST014       Sneha Banerjee   Ballygunge  2023-10-05       Gold
14    CUST015      Rohan Mukherjee     Gariahat  2023-07-03    Regular
15    CUST016       Suroj Banerjee    Salt Lake  2025-02-09    Ragular
16    CUST017      Rohan Mukherjee    Salt Lake  2024-07-31     Silver
17    CUST018             Amit Roy       Behala  2024-01-29     Silver
18    CUST019          Rohan Dutta       Behala  2023-02-24       Gold
20    CUST021          Piyali Bose      Dum Dum  2025-03-03    Regular
21    CUST022      Suroj Mukherjee   Ballygunge  2024-05-17     Silver
22    CUST023           Riya Dutta      Dum Dum  2024-03-18     Silver
24    CUST025      Ishita Banerjee  Park Street  2023-03-26    Regular
25    CUST026        Debashish Roy    Salt Lake  2025-01-27    Ragular
26    CUST027    Souvik Chatterjee  Park Street  2023-04-04       Gold
27    CUST028           Ishita Sen       Behala  2025-02-18    Regular
28    CUST029            Priya Das  Park Street  2023-07-11    Ragular
29    CUST030          Kunal Dutta      Dum Dum  2023-04-16       Gold
31    CUST032           Souvik Roy     Gariahat  2023-10-26    Ragular
33    CUST034          Moumita Roy    Salt Lake  2023-05-23    Regular
34    CUST035     Ishita Mukherjee   Ballygunge  2023-05-30       Gold
35    CUST036          Moumita Roy       Howrah  2024-03-07    Regular
36    CUST037         Sohini Ghosh       Behala  2023-09-15     Silver
37    CUST038          Sohini Bose   New Market  2024-04-13       Gold
38    CUST039  Debashish Mukherjee     Gariahat  2024-02-10    Regular
39    CUST040           Piyali Roy       Behala  2024-03-26    Regular
40    CUST041         Poulomi Bose    Salt Lake  2023-11-04    Regular
41    CUST042      Piyali Banerjee   Ballygunge  2023-11-18     Silver
42    CUST043      Abir Chatterjee       Howrah  2025-01-22    Ragular
43    CUST044        Amit Banerjee       Behala  2024-01-21    Regular
44    CUST045      Abir Chatterjee  Park Street  2024-07-31     Silver
46    CUST047            Suroj Sen   New Market  2024-03-24    Regular
47    CUST048            Rohan Roy   Ballygunge  2023-05-23    Regular
48    CUST049      Sneha Mukherjee    Salt Lake  2025-01-02    Ragular
49    CUST050           Abir Ghosh   Ballygunge  2024-09-04    Ragular
50    CUST051             Amit Roy      Dum Dum  2024-07-10       Gold
51    CUST052           Riya Dutta  Park Street  2023-04-22     Silver
52    CUST053             Riya Das     Gariahat  2024-07-30    Ragular
53    CUST054           Souvik Roy  Park Street  2023-01-11       Gold
54    CUST055      Tanmoy Banerjee   New Market  2024-04-01    Regular
55    CUST056             Abir Sen    Salt Lake  2023-12-20       Gold
56    CUST057         Sohini Ghosh       Howrah  2024-03-01       Gold
57    CUST058            Priya Das       Behala  2023-11-16    Regular
58    CUST059       Kunal Banerjee   Ballygunge  2023-12-23    Ragular
59    CUST060            Priya Sen   Ballygunge  2023-11-23       Gold

In [13]:
k = pd.merge(Kc,k_s, on='CustomerID', how='left')

In [14]:
k

,CustomerID,CustomerName,HomeArea,JoinDate,Membership,TransactionID,OrderDate,Area,Product,Category,Qty,UnitPrice,PaymentMode
0,CUST001,Debashish Karmakar,New Market,2024-06-01,Ragular,TXN0139,2025-07-14,Dum Dum,Punjabi,Clothing,1.0,300.0,Card
1,CUST002,Riya Karmakar,Ballygunge,2024-11-06,Ragular,TXN0019,2025-12-29,New Market,Fish (Rui),Food,1.0,250.0,Card
2,CUST002,Riya Karmakar,Ballygunge,2024-11-06,Ragular,TXN0056,2025-06-02,Ballygunge,Rosogolla Tin,Food,1.0,800.0,UPI
3,CUST002,Riya Karmakar,Ballygunge,2024-11-06,Ragular,TXN0059,2025-04-04,Dum Dum,Kurti,Clothing,1.0,NaN,UPI
4,CUST002,Riya Karmakar,Ballygunge,2024-11-06,Ragular,TXN0185,2025-10-11,BEHALA,Tea Packet,Grocery,2.0,300.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,CUST060,Priya Sen,Ballygunge,2023-11-23,Gold,TXN0016,2025-04-05,HOWRAH,Tea Packet,Grocery,1.0,150.0,UPI
254,CUST060,Priya Sen,Ballygunge,2023-11-23,Gold,TXN0096,2025-10-20,New Market,Tea Packet,Grocery,NaN,450.0,UPI
255,CUST060,Priya Sen,Ballygunge,2023-11-23,Gold,TXN0215,2025-09-02,Dum Dum,Sweets Box,Food,NaN,NaN,Card
256,CUST060,Priya Sen,Ballygunge,2023-11-23,Gold,TXN0217,2025-04-06,dum dum,Saree,Clothing,5.0,NaN,Cash
257,CUST060,Priya Sen,Ballygunge,2023-11-23,Gold,TXN0222,2025-05-01,Gariahat,Fish (Rui),Food,2.0,1200.0,Card

In [18]:
k = k.reset_index(drop=True)

In [19]:
k

,CustomerID,CustomerName,HomeArea,JoinDate,Membership,TransactionID,OrderDate,Area,Product,Category,Qty,UnitPrice,PaymentMode
0,CUST001,Debashish Karmakar,New Market,2024-06-01,Ragular,TXN0139,2025-07-14,Dum Dum,Punjabi,Clothing,1.0,300.0,Card
1,CUST002,Riya Karmakar,Ballygunge,2024-11-06,Ragular,TXN0019,2025-12-29,New Market,Fish (Rui),Food,1.0,250.0,Card
2,CUST002,Riya Karmakar,Ballygunge,2024-11-06,Ragular,TXN0056,2025-06-02,Ballygunge,Rosogolla Tin,Food,1.0,800.0,UPI
3,CUST002,Riya Karmakar,Ballygunge,2024-11-06,Ragular,TXN0059,2025-04-04,Dum Dum,Kurti,Clothing,1.0,NaN,UPI
4,CUST002,Riya Karmakar,Ballygunge,2024-11-06,Ragular,TXN0185,2025-10-11,BEHALA,Tea Packet,Grocery,2.0,300.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,CUST060,Priya Sen,Ballygunge,2023-11-23,Gold,TXN0016,2025-04-05,HOWRAH,Tea Packet,Grocery,1.0,150.0,UPI
254,CUST060,Priya Sen,Ballygunge,2023-11-23,Gold,TXN0096,2025-10-20,New Market,Tea Packet,Grocery,NaN,450.0,UPI
255,CUST060,Priya Sen,Ballygunge,2023-11-23,Gold,TXN0215,2025-09-02,Dum Dum,Sweets Box,Food,NaN,NaN,Card
256,CUST060,Priya Sen,Ballygunge,2023-11-23,Gold,TXN0217,2025-04-06,dum dum,Saree,Clothing,5.0,NaN,Cash
257,CUST060,Priya Sen,Ballygunge,2023-11-23,Gold,TXN0222,2025-05-01,Gariahat,Fish (Rui),Food,2.0,1200.0,Card

In [20]:
k.to_csv('Kolkata_sales_customers.csv', index=False)